kong:
  adminPort: 8001
  image:
    repository: kong/kong
    tag: "3.5"
    pullPolicy: IfNotPresent
  env:
    pg_host: kongdb-postgresql
    pg_user: kong
    pg_password: kong
    pg_database: kong
    database: postgres
    role: control_plane
    cluster_cert: /etc/secrets/kong-cluster-cert-secret/tls.crt
    cluster_cert_key: /etc/secrets/kong-cluster-cert-secret/tls.key
  admin:
    enabled: true
    http:
      enabled: true
      servicePort: 8001
      containerPort: 8001
  cluster:
    enabled: true
    tls:
      enabled: true
      servicePort: 8005
      containerPort: 8005
  proxy:
    enabled: false
  secretVolumes:
  - kong-cluster-cert-secret

  postgresql:
    enabled: false

  ingressController:
    enabled: false

volumes:
  - name: kong-cluster-cert-secret
    secret:
      secretName: kong-cluster-cert-secret